---
- hosts: dev
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        start: present
    - name: Start the container
      docker_container:
         name: sample-app
         image: "sandeepreddy1992/docker-ansbile-app:{{DOCKER_TAG}}"
         state: started
         published_ports:
         - 0.0.0.0:8080:8080
